### ISSUE TITLE
Some Mastodon 2.8.0 changes (compared to 2.8.0 rc1) in identity proofs not merged

### ISSUE THREAD

**Issue by PeterCxy** [gled-rs/mastodon#12]
I came across some problems while adding identity proofs, and it was caused by https://github.com/tootsuite/mastodon/commit/154106c0c3b8fdd64f739fc449203b842924df0c not being merged into this fork of Mastodon. I checked the commit history and it seems that only Mastodon 2.8.0rc1 is merged here. Can you please merge this commit so at least identity proofs will work properly?

**Comment by gled-rs** [comment]
already merged in a previous update :)
