### ISSUE TITLE
"error: corrupt patch" for Postgres FTS

### ISSUE THREAD

**Issue by angristan** [gled-rs/mastodon#17]
Using https://gist.sigpipe.me/dashie/a84a976a13ff6ae97da494fc7a657d10221e7368#file_good.patch:

```
mastodon@masto ~/live> git apply ../good.patch
error: corrupt patch at line 33
```

Using https://github.com/gled-rs/mastodo/blob/master/docs/no_es.patch:

```
mastodon@masto ~/live> git apply ../no_es.patch
error: corrupt patch at line 42
```

In both cases the line is 

```
diff --git a/app/services/search_service.rb b/app/services/search_service.rb
```

I'm running v2.9.2. Is the patch up-to-date?

**Comment by rhaamo** [comment]
Update for which version ? Glitch ? Tootsuite ? Mastodo ?

For Mastodo the FTS is already builtin https://github.com/gled-rs/mastodo/blob/master/app/services/search_service.rb#L18

For tootsuite/glitch, my patch should pass.

Worst case you have to apply by hand.

But looking at the search_service.rb from patch and my patched glitch, both are the same. I dunno why the patch fails.

Also `no_es.patch` isn't updated at all.

**Comment by angristan** [comment]
Oh sorry, i'm running tootsuite.

I'll try to make a patch by myself :slightly_smiling_face:

**Comment by angristan** [comment]
This is working for me:

```patch
diff --git a/app/models/status.rb b/app/models/status.rb
index fb9bbc9a9..f7718a14f 100644
--- a/app/models/status.rb
+++ b/app/models/status.rb
@@ -268,6 +268,13 @@ class Status < ApplicationRecord
   after_create :set_poll_id

   class << self
+    def search_for(term, limit = 20)
+      pattern = sanitize_sql_like(term)
+      pattern = "#{pattern}"
+      Status.unscoped {
+        Status.where('tsv @@ plainto_tsquery(?)', pattern).where(visibility: [:public]).order(updated_at: :desc).limit(limit)
+      }
+    end
     def selectable_visibilities
       visibilities.keys - %w(direct limited)
     end
diff --git a/app/services/search_service.rb b/app/services/search_service.rb
index e0da61dac..f3aaae9e1 100644
--- a/app/services/search_service.rb
+++ b/app/services/search_service.rb
@@ -16,6 +16,7 @@ class SearchService < BaseService
         results[:accounts] = perform_accounts_search! if account_searchable?
         results[:statuses] = perform_statuses_search! if full_text_searchable?
         results[:hashtags] = perform_hashtags_search! if hashtag_searchable?
+       results[:statuses] = Status.search_for(query.gsub(/\A#/, ''), limit) unless query.start_with?('@') or query.start_with?('#')
       end
     end
   end
````

Is there a way to display more than 5 toots in the results? :)

**Comment by rhaamo** [comment]
Your diff is missing the edits in `app/controllers/api/v2/search_controller.rb` and `app/controllers/api/v1/search_controller.rb`, are they the same of my patch ?

The limit should be `RESULT_LIMIT = 20` in `app/controllers/api/v1/search_controller.rb` by default

**Comment by angristan** [comment]
I didn't need to edit `app/controllers/api/v1/search_controller.rb` because I already have the same content (https://github.com/tootsuite/mastodon/blob/master/app/controllers/api/v1/search_controller.rb).

I did not see `app/controllers/api/v2/search_controller.rb` in your patch though?

**Comment by rhaamo** [comment]
Oh, didn't saw for the v1, and for the v2 it seems to be ok too.

I've updated my patch, thanks !

**Comment by angristan** [comment]
When you talk about your patch, which one are you talking about ? :thinking: 

Also, does `RESULT_LIMIT = 20` have any effect? Don't you have 5 toots in your search results too?

**Comment by rhaamo** [comment]
My patch is this one https://gist.sigpipe.me/dashie/a84a976a13ff6ae97da494fc7a657d10221e7368

And for the search limit I got 10 on a random search, so it seems to be ok.

So maybe your term really doesn't returns that much results, or tootsuite might have some other limitation somewhere.

**Comment by angristan** [comment]
Ok, maybe it's a limitation on the front-end... :cry:

**Comment by rhaamo** [comment]
`/api/v2/search?q=potat&resolve=true&limit=10` is the call made from the frontend, the potat resolved to 10 accounts and 10 statuses too.

I guess you can change it here https://github.com/tootsuite/mastodon/blob/ca8944728f4568bbef8edae99382cd44cbc144d6/app/javascript/mastodon/actions/search.js#L36 but I'm no mastodon frontend expert

**Comment by angristan** [comment]
I ended up with this patch:

```patch
diff --git a/app/javascript/mastodon/actions/search.js b/app/javascript/mastodon/actions/search.js
index 7c06670eb..ee7bc1657 100644
--- a/app/javascript/mastodon/actions/search.js
+++ b/app/javascript/mastodon/actions/search.js
@@ -37,7 +37,7 @@ export function submitSearch() {
       params: {
         q: value,
         resolve: true,
-        limit: 5,
+        limit: 20,
       },
     }).then(response => {
       if (response.data.accounts) {
diff --git a/app/models/status.rb b/app/models/status.rb
index fb9bbc9a9..f7718a14f 100644
--- a/app/models/status.rb
+++ b/app/models/status.rb
@@ -268,6 +268,13 @@ class Status < ApplicationRecord
   after_create :set_poll_id
 
   class << self
+    def search_for(term, limit = 20)
+      pattern = sanitize_sql_like(term)
+      pattern = "#{pattern}"
+      Status.unscoped {
+        Status.where('tsv @@ plainto_tsquery(?)', pattern).where(visibility: [:public]).order(updated_at: :desc).limit(limit)
+      }
+    end
     def selectable_visibilities
       visibilities.keys - %w(direct limited)
     end
diff --git a/app/services/search_service.rb b/app/services/search_service.rb
index e0da61dac..f3aaae9e1 100644
--- a/app/services/search_service.rb
+++ b/app/services/search_service.rb
@@ -16,6 +16,7 @@ class SearchService < BaseService
         results[:accounts] = perform_accounts_search! if account_searchable?
         results[:statuses] = perform_statuses_search! if full_text_searchable?
         results[:hashtags] = perform_hashtags_search! if hashtag_searchable?
+       results[:statuses] = Status.search_for(query.gsub(/\A#/, ''), limit) unless query.start_with?('@') or query.start_with?('#')
       end
     end
   end
```

It's nice to finally experience real search.

**Comment by angristan** [comment]
I made PR just in case: https://github.com/gled-rs/mastodo/pull/18
