### ISSUE TITLE
[BUG] Local timeline index is broken due to showing replies & boosts

### ISSUE THREAD

**Issue by PeterCxy** [gled-rs/mastodon#22]
in <https://github.com/tootsuite/mastodon/pull/11648> a new index was introduced for local timeline to fix slow local timeline query reported in <https://github.com/tootsuite/mastodon/issues/11643>, but on this fork the index was invalidated because we do not have `reblog_of_id IS NULL AND ((NOT reply) OR (in_reply_to_account_id = account_id))` part in the query.

On my instance the local timeline stopped working due to exactly this issue. Please consider removing the extraneous part of the index condition (in `db/schema.rb` and `db/migrate/20190823221802_add_local_index_to_statuses.rb`) so local timelines work fine. Here is a commit by someone that seem to fix this exact problem <https://github.com/AstroProfundis/mastodon/commit/9a07b50e07d2d2e3092b1b45e1eeb23016f0b362>

**Comment by gled-rs** [comment]
Thanks for the report, but this repo is closing, please see readme.
